In [ ]:
# imports e configurações

import os
import pandas as pd
import seaborn as sns
import kagglehub
import shutil
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

os.environ["KAGGLE_USERNAME"] = os.getenv("KAGGLE_USERNAME")
os.environ["KAGGLE_KEY"] = os.getenv("KAGGLE_KEY")

sns.set_theme(style="darkgrid")
pd.set_option("display.max_columns", None)

# Download do dataset

RAW_DIR = Path("../data/raw")
RAW_DIR.mkdir(parents=True, exist_ok=True)

print("baixando dataset...")
path =  kagglehub.dataset_download("maharshipandya/-spotify-tracks-dataset")

for arquivo in Path(path).glob("*.csv"):
    destino = RAW_DIR / arquivo.name
    shutil.copy2(arquivo, destino)
    print(f"arquivo copiado para {destino}")

baixando dataset...
Downloading to C:\Users\vidal\.cache\kagglehub\datasets\maharshipandya\-spotify-tracks-dataset\1.archive...

100%|██████████| 8.17M/8.17M [00:01<00:00, 5.42MB/s]

Extracting files...

arquivo copiado para ..\data\raw\dataset.csv

In [5]:
# leitura do arquivo

df = pd.read_csv("../data/raw/dataset.csv", index_col=0)
print(f"Linhas: {df.shape[0]:,} | Colunas: {df.shape[1]}")
df.head()

Linhas: 114,000 | Colunas: 20

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,0.4610,1,-6.746,0,0.1430,0.0322,0.000001,0.3580,0.715,87.917,4,acoustic
1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,0.1660,1,-17.235,1,0.0763,0.9240,0.000006,0.1010,0.267,77.489,4,acoustic
2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,0.3590,0,-9.734,1,0.0557,0.2100,0.000000,0.1170,0.120,76.332,4,acoustic
3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,0.0596,0,-18.515,1,0.0363,0.9050,0.000071,0.1320,0.143,181.740,3,acoustic
4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,0.4430,2,-9.681,1,0.0526,0.4690,0.000000,0.0829,0.167,119.949,4,acoustic

In [4]:
print("=== TIPOS DE DADOS ===")
print(df.dtypes)

print("\n=== VALORES NULOS ===")
nulos = df.isnull().sum()
print(nulos[nulos > 0])

print("\n=== DUPLICATAS ===")
print(f"Linhas duplicadas: {df.duplicated().sum():,}")

print("\n=== ESTATÍSTICAS GERAIS ===")
df.describe().round(3)

=== TIPOS DE DADOS ===
track_id                str
artists                 str
album_name              str
track_name              str
popularity            int64
duration_ms           int64
explicit               bool
danceability        float64
energy              float64
key                   int64
loudness            float64
mode                  int64
speechiness         float64
acousticness        float64
instrumentalness    float64
liveness            float64
valence             float64
tempo               float64
time_signature        int64
track_genre             str
dtype: object

=== VALORES NULOS ===
artists       1
album_name    1
track_name    1
dtype: int64

=== DUPLICATAS ===
Linhas duplicadas: 450

=== ESTATÍSTICAS GERAIS ===

,popularity,duration_ms,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature
count,114000.000,114000.000,114000.000,114000.000,114000.000,114000.000,114000.000,114000.000,114000.000,114000.000,114000.000,114000.000,114000.000,114000.000
mean,33.239,228029.153,0.567,0.641,5.309,-8.259,0.638,0.085,0.315,0.156,0.214,0.474,122.148,3.904
std,22.305,107297.713,0.174,0.252,3.560,5.029,0.481,0.106,0.333,0.310,0.190,0.259,29.978,0.433
min,0.000,0.000,0.000,0.000,0.000,-49.531,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
25%,17.000,174066.000,0.456,0.472,2.000,-10.013,0.000,0.036,0.017,0.000,0.098,0.260,99.219,4.000
50%,35.000,212906.000,0.580,0.685,5.000,-7.004,1.000,0.049,0.169,0.000,0.132,0.464,122.017,4.000
75%,50.000,261506.000,0.695,0.854,8.000,-5.003,1.000,0.084,0.598,0.049,0.273,0.683,140.071,4.000
max,100.000,5237295.000,0.985,1.000,11.000,4.532,1.000,0.965,0.996,1.000,1.000,0.995,243.372,5.000